export type ReferenceProduct = "openclaw" | "hermes" | "codex" | "claude-code";
export type ParityStatus = "implemented" | "partial" | "planned";

export interface CapabilityCatalogEntry {
  id: string;
  category: "surfaces" | "sessions" | "memory" | "tools" | "extensions" | "orchestration" | "providers" | "safety" | "engineering";
  capability: string;
  referenceProducts: ReferenceProduct[];
  status: ParityStatus;
  evidence: string[];
  gap?: string;
}

export const PARITY_SOURCE_SNAPSHOT = {
  checkedAt: "2026-07-22",
  openclaw: [
    "https://docs.openclaw.ai/concepts/features",
    "https://docs.openclaw.ai/tools",
    "https://docs.openclaw.ai/concepts/session-tool",
    "https://docs.openclaw.ai/concepts/memory"
  ],
  hermes: [
    "https://github.com/NousResearch/hermes-agent",
    "https://github.com/NousResearch/hermes-agent/blob/main/website/docs/developer-guide/programmatic-integration.md"
  ],
  codex: [
    "https://openai.com/codex/",
    "https://openai.com/index/introducing-the-codex-app/",
    "https://github.com/openai/codex/blob/main/codex-rs/core/config.schema.json"
  ],
  "claude-code": [
    "https://code.claude.com/docs/en/how-claude-code-works",
    "https://code.claude.com/docs/en/features-overview",
    "https://code.claude.com/docs/en/tools-reference"
  ]
} as const;

export const CAPABILITY_CATALOG: CapabilityCatalogEntry[] = [
  { id: "surface.desktop", category: "surfaces", capability: "Native desktop command center", referenceProducts: ["openclaw", "hermes", "codex", "claude-code"], status: "implemented", evidence: ["apps/desktop/src/main/index.ts", "apps/desktop/src/preload/index.ts", "apps/desktop/src/renderer/App.tsx", "scripts/smoke-desktop.mjs"] },
  { id: "surface.terminal", category: "surfaces", capability: "Interactive CLI and full-screen TUI", referenceProducts: ["openclaw", "hermes", "codex", "claude-code"], status: "implemented", evidence: ["apps/cli/src/index.ts", "apps/cli/src/tui.ts", "apps/cli/src/arguments.ts", "apps/cli/src/arguments.test.ts", "apps/cli/build.mjs", "scripts/smoke-packaged-cli.mjs"] },
  { id: "surface.ide", category: "surfaces", capability: "VS Code, JetBrains, and ACP editor integration", referenceProducts: ["hermes", "codex", "claude-code"], status: "implemented", evidence: ["packages/agent-core/src/acp.ts", "packages/agent-core/src/acp.test.ts", "apps/cli/src/acp-stdio.ts", "apps/cli/src/acp-entry.ts", "editors/vscode-kestrel/extension.js", "editors/vscode-kestrel/package.json", "editors/jetbrains-kestrel/src/main/java/dev/kestrel/jetbrains/KestrelToolWindowFactory.java", "editors/jetbrains-kestrel/src/main/resources/META-INF/plugin.xml", "scripts/verify-editor-integrations.mjs", "scripts/smoke-packaged-cli.mjs"] },
  { id: "surface.web-cloud", category: "surfaces", capability: "Authenticated web and cloud task surface", referenceProducts: ["openclaw", "hermes", "codex", "claude-code"], status: "implemented", evidence: ["packages/agent-core/src/remote.ts", "packages/agent-core/src/remote-http.ts", "packages/agent-core/src/remote-web.ts", "packages/agent-core/src/remote-http.test.ts", "apps/cli/src/index.ts", "scripts/smoke-packaged-cli.mjs"] },
  { id: "surface.mobile-remote", category: "surfaces", capability: "Mobile supervision and remote control", referenceProducts: ["openclaw", "codex", "claude-code"], status: "implemented", evidence: ["packages/agent-core/src/remote.ts", "packages/agent-core/src/remote-http.ts", "packages/agent-core/src/remote-web.ts", "packages/agent-core/src/remote-http.test.ts", "apps/cli/src/index.ts", "scripts/smoke-packaged-cli.mjs"] },
  { id: "surface.channels", category: "surfaces", capability: "Messaging gateway across chat and email channels", referenceProducts: ["openclaw", "hermes", "codex", "claude-code"], status: "implemented", evidence: ["packages/agent-core/src/channels.ts", "packages/agent-core/src/channels.test.ts", "packages/agent-core/src/remote-http.ts", "apps/desktop/src/renderer/App.tsx", "scripts/smoke-packaged-cli.mjs"] },
  { id: "surface.streaming-steering", category: "surfaces", capability: "Streaming tool output, interruption, and mid-turn steering", referenceProducts: ["openclaw", "hermes", "codex", "claude-code"], status: "implemented", evidence: ["packages/agent-core/src/runtime.ts", "packages/agent-core/src/agent-loop.ts", "packages/agent-core/src/agent-core.test.ts", "apps/desktop/src/renderer/App.tsx", "apps/cli/src/tui.ts"] },
  { id: "surface.multimodal", category: "surfaces", capability: "Image, audio, video, document, and voice input/output", referenceProducts: ["openclaw", "hermes", "codex", "claude-code"], status: "implemented", evidence: ["packages/agent-core/src/providers/types.ts", "packages/agent-core/src/providers/gemini-generate-content.ts", "packages/agent-core/src/providers/providers.test.ts", "packages/agent-core/src/media-providers.ts", "packages/agent-core/src/media-artifacts.test.ts", "packages/agent-core/src/agent-core.test.ts", "apps/desktop/src/main/index.ts", "apps/desktop/src/renderer/App.tsx"] },

  { id: "session.persistence", category: "sessions", capability: "Durable sessions with list and resume", referenceProducts: ["openclaw", "hermes", "codex", "claude-code"], status: "implemented", evidence: ["packages/agent-core/src/runtime.ts", "packages/agent-core/src/agent-loop.ts", "packages/database/src/index.ts", "apps/desktop/src/renderer/App.tsx", "apps/cli/src/index.ts"] },
  { id: "session.fork-checkpoint", category: "sessions", capability: "Fork, checkpoint, resume, and cancel lifecycle", referenceProducts: ["openclaw", "hermes", "codex", "claude-code"], status: "implemented", evidence: ["packages/agent-core/src/runtime.ts", "packages/agent-core/src/runtime.test.ts", "apps/desktop/src/renderer/App.tsx", "apps/cli/src/index.ts"] },
  { id: "session.undo-retry", category: "sessions", capability: "Turn retry, undo, rewind, and filesystem restoration", referenceProducts: ["hermes", "codex", "claude-code"], status: "implemented", evidence: ["packages/agent-core/src/runtime.ts", "packages/agent-core/src/agent-loop.ts", "packages/agent-core/src/runtime.test.ts", "packages/agent-core/src/agent-core.test.ts", "apps/desktop/src/renderer/App.tsx", "apps/cli/src/index.ts"] },
  { id: "session.compaction", category: "sessions", capability: "Automatic context compaction and usage inspection", referenceProducts: ["openclaw", "hermes", "codex", "claude-code"], status: "implemented", evidence: ["packages/agent-core/src/context-compactor.ts", "packages/agent-core/src/agent-loop.ts", "packages/agent-core/src/agent-loop.test.ts", "packages/database/migrations/004_agent_loop.sql", "apps/desktop/src/renderer/App.tsx"] },
  { id: "session.instructions", category: "sessions", capability: "Hierarchical project instruction and rule files", referenceProducts: ["openclaw", "hermes", "codex", "claude-code"], status: "implemented", evidence: ["packages/agent-core/src/runtime.ts", "packages/agent-core/src/runtime.test.ts"] },

  { id: "memory.durable", category: "memory", capability: "Local durable episodic, semantic, procedural, project, and relationship memory", referenceProducts: ["openclaw", "hermes", "codex", "claude-code"], status: "implemented", evidence: ["packages/database/src/index.ts", "packages/agent-core/src/memory.ts", "packages/agent-core/src/memory.test.ts", "apps/desktop/src/renderer/App.tsx"] },
  { id: "memory.session-search", category: "memory", capability: "Cross-session full-text and semantic transcript search", referenceProducts: ["openclaw", "hermes", "codex", "claude-code"], status: "implemented", evidence: ["packages/database/src/index.ts", "packages/database/migrations/003_runtime_history.sql", "packages/agent-core/src/runtime.ts", "packages/agent-core/src/semantic-search.ts", "packages/agent-core/src/memory.test.ts", "apps/desktop/src/renderer/App.tsx"] },
  { id: "memory.user-model", category: "memory", capability: "User profile, preference, and relationship modeling", referenceProducts: ["openclaw", "hermes"], status: "implemented", evidence: ["packages/agent-core/src/user-model.ts", "packages/agent-core/src/user-model.test.ts", "packages/agent-core/src/memory.ts", "packages/agent-core/src/memory.test.ts", "apps/desktop/src/renderer/App.tsx"] },
  { id: "memory.self-learning", category: "memory", capability: "Agent-created and self-improving skills from experience", referenceProducts: ["openclaw", "hermes", "codex", "claude-code"], status: "implemented", evidence: ["packages/agent-core/src/extensions/skills.ts", "packages/agent-core/src/extensions/skill-learning.ts", "packages/agent-core/src/extensions/extensions.test.ts", "apps/desktop/src/renderer/App.tsx"] },

  { id: "tool.workspace-read", category: "tools", capability: "Allowlisted workspace list, read, and text search", referenceProducts: ["openclaw", "hermes", "codex", "claude-code"], status: "implemented", evidence: ["packages/agent-core/src/runtime.ts", "packages/agent-core/src/runtime.test.ts", "apps/desktop/src/main/workspace-grant-store.ts", "apps/desktop/src/main/index.ts", "apps/desktop/src/renderer/App.tsx"] },
  { id: "tool.workspace-write", category: "tools", capability: "Create, edit, patch, move, and delete workspace files", referenceProducts: ["openclaw", "hermes", "codex", "claude-code"], status: "implemented", evidence: ["packages/agent-core/src/runtime.ts", "packages/agent-core/src/runtime.test.ts", "apps/desktop/src/main/workspace-grant-store.ts", "apps/desktop/src/renderer/App.tsx"] },
  { id: "tool.shell-process", category: "tools", capability: "Sandboxed shell, terminal, and long-running process control", referenceProducts: ["openclaw", "hermes", "codex", "claude-code"], status: "implemented", evidence: ["packages/agent-core/src/command-runner.ts", "packages/agent-core/src/runtime.ts", "packages/agent-core/src/runtime.test.ts"] },
  { id: "tool.git-worktree", category: "tools", capability: "Git diff, commit, branch, PR, and isolated worktree workflows", referenceProducts: ["hermes", "codex", "claude-code"], status: "implemented", evidence: ["packages/agent-core/src/runtime.ts", "packages/agent-core/src/command-runner.ts", "packages/agent-core/src/runtime.test.ts", "apps/desktop/src/main/credential-broker.ts"] },
  { id: "tool.web", category: "tools", capability: "Web search and readable fetch", referenceProducts: ["openclaw", "hermes", "codex", "claude-code"], status: "implemented", evidence: ["packages/agent-core/src/web-tools.ts", "packages/agent-core/src/web-tools.test.ts", "apps/cli/src/state.ts", "apps/desktop/src/utility/index.ts", "apps/desktop/src/renderer/App.tsx"] },
  { id: "tool.browser-computer", category: "tools", capability: "Isolated browser automation and computer use", referenceProducts: ["openclaw", "hermes", "codex", "claude-code"], status: "implemented", evidence: ["packages/agent-core/src/browser-automation.ts", "packages/agent-core/src/browser-automation.test.ts", "apps/desktop/src/main/electron-browser-service.ts", "apps/desktop/src/utility/index.ts", "scripts/smoke-desktop.mjs"] },
  { id: "tool.code-intelligence", category: "tools", capability: "Language-server diagnostics, definitions, and references", referenceProducts: ["codex", "claude-code"], status: "implemented", evidence: ["packages/agent-core/src/code-intelligence.ts", "packages/agent-core/src/code-intelligence.test.ts", "apps/cli/src/index.ts", "apps/desktop/src/utility/index.ts"] },
  { id: "tool.media-artifacts", category: "tools", capability: "Media generation/analysis and document artifact workflows", referenceProducts: ["openclaw", "codex", "claude-code"], status: "implemented", evidence: ["packages/agent-core/src/media-artifacts.ts", "packages/agent-core/src/media-providers.ts", "packages/agent-core/src/media-artifacts.test.ts", "apps/cli/src/state.ts", "apps/desktop/src/utility/index.ts", "apps/desktop/src/renderer/App.tsx"] },
  { id: "tool.discovery", category: "tools", capability: "Typed tool catalog, policy filtering, and query discovery", referenceProducts: ["openclaw", "hermes", "codex", "claude-code"], status: "implemented", evidence: ["packages/agent-core/src/runtime.ts", "packages/agent-core/src/runtime.test.ts", "packages/shared-types/src/contracts.ts"] },

  { id: "extension.mcp-client", category: "extensions", capability: "MCP client for external tools and resources", referenceProducts: ["openclaw", "hermes", "codex", "claude-code"], status: "implemented", evidence: ["packages/agent-core/src/extensions/mcp.ts", "packages/agent-core/src/extensions/plugin-mcp.ts", "packages/agent-core/src/extensions/extensions.test.ts"] },
  { id: "extension.protocol-server", category: "extensions", capability: "Embeddable MCP, ACP, JSON-RPC, SDK, and HTTP agent protocols", referenceProducts: ["openclaw", "hermes", "codex", "claude-code"], status: "implemented", evidence: ["packages/agent-core/src/extensions/mcp.ts", "packages/agent-core/src/extensions/extensions.test.ts", "packages/agent-core/src/acp.ts", "packages/agent-core/src/acp.test.ts", "packages/agent-core/src/remote-http.ts", "packages/agent-core/src/remote-http.test.ts", "apps/cli/src/acp-stdio.ts", "scripts/smoke-packaged-cli.mjs"] },
  { id: "extension.skills", category: "extensions", capability: "Agent Skills-compatible reusable instructions and workflows", referenceProducts: ["openclaw", "hermes", "codex", "claude-code"], status: "implemented", evidence: ["packages/agent-core/src/extensions/skills.ts", "packages/agent-core/src/extensions/skill-learning.ts", "packages/agent-core/src/extensions/extensions.test.ts", "packages/agent-core/src/extensions/plugins.ts", "apps/desktop/src/renderer/App.tsx"] },
  { id: "extension.plugins", category: "extensions", capability: "Installable plugins and marketplace packaging", referenceProducts: ["openclaw", "hermes", "codex", "claude-code"], status: "implemented", evidence: ["packages/agent-core/src/extensions/plugins.ts", "packages/agent-core/src/extensions/plugin-installer.ts", "packages/agent-core/src/extensions/plugin-mcp.ts", "packages/agent-core/src/extensions/plugin-installer.test.ts", "packages/agent-core/src/extensions/extensions.test.ts", "apps/desktop/src/main/plugin-trust-store.ts", "apps/desktop/src/main/index.ts", "apps/desktop/src/renderer/App.tsx"] },
  { id: "extension.hooks", category: "extensions", capability: "Pre-tool, post-tool, and tool-error lifecycle hooks", referenceProducts: ["openclaw", "hermes", "codex", "claude-code"], status: "implemented", evidence: ["packages/agent-core/src/runtime.ts", "packages/agent-core/src/runtime.test.ts"] },
  { id: "extension.personality", category: "extensions", capability: "User-selectable agent personalities and custom agents", referenceProducts: ["openclaw", "hermes", "codex", "claude-code"], status: "implemented", evidence: ["packages/agent-core/src/personality.ts", "packages/agent-core/src/index.ts", "packages/agent-core/src/agent-loop.ts", "packages/agent-core/src/agent-core.test.ts", "apps/desktop/src/renderer/App.tsx"] },

  { id: "orchestration.subagents", category: "orchestration", capability: "Isolated subagents with scoped tools and context", referenceProducts: ["openclaw", "hermes", "codex", "claude-code"], status: "implemented", evidence: ["packages/agent-core/src/orchestration.ts", "packages/agent-core/src/orchestration.test.ts", "apps/desktop/src/renderer/App.tsx"] },
  { id: "orchestration.teams", category: "orchestration", capability: "Parallel agent teams, swarms, and peer messaging", referenceProducts: ["openclaw", "hermes", "codex", "claude-code"], status: "implemented", evidence: ["packages/agent-core/src/orchestration.ts", "packages/agent-core/src/orchestration.test.ts", "apps/desktop/src/renderer/App.tsx"] },
  { id: "orchestration.tasks-goals", category: "orchestration", capability: "Plans, goals, task lists, and opportunity governance", referenceProducts: ["openclaw", "hermes", "codex", "claude-code"], status: "implemented", evidence: ["packages/agent-core/src/orchestration.ts", "packages/agent-core/src/orchestration.test.ts", "apps/desktop/src/renderer/App.tsx"] },
  { id: "orchestration.background", category: "orchestration", capability: "Background and cloud execution with review queue", referenceProducts: ["openclaw", "hermes", "codex", "claude-code"], status: "implemented", evidence: ["packages/agent-core/src/orchestration.ts", "packages/agent-core/src/orchestration.test.ts", "apps/cli/src/index.ts", "apps/desktop/src/utility/index.ts", "apps/desktop/src/main/core-supervisor.ts", "apps/desktop/src/main/index.ts", "apps/desktop/src/renderer/App.tsx", "scripts/smoke-packaged-cli.mjs"] },
  { id: "orchestration.schedule", category: "orchestration", capability: "Cron, natural-language automations, webhooks, and heartbeat", referenceProducts: ["openclaw", "hermes", "codex", "claude-code"], status: "implemented", evidence: ["packages/agent-core/src/orchestration.ts", "packages/agent-core/src/orchestration.test.ts", "packages/agent-core/src/index.ts", "packages/agent-core/src/remote-http.ts", "apps/cli/src/arguments.ts", "apps/desktop/src/renderer/App.tsx", "scripts/smoke-packaged-cli.mjs"] },
  { id: "orchestration.code-mode", category: "orchestration", capability: "Programmatic tool composition and resumable workflows", referenceProducts: ["openclaw", "hermes", "codex"], status: "implemented", evidence: ["packages/agent-core/src/orchestration.ts", "packages/agent-core/src/orchestration.test.ts"] },

  { id: "provider.multi-model", category: "providers", capability: "Production multi-provider, local-model, and subscription authentication", referenceProducts: ["openclaw", "hermes", "codex", "claude-code"], status: "implemented", evidence: ["packages/agent-core/src/providers/openai-responses.ts", "packages/agent-core/src/providers/anthropic-messages.ts", "packages/agent-core/src/providers/gemini-generate-content.ts", "packages/agent-core/src/providers/ollama-chat.ts", "packages/agent-core/src/providers/subscription-cli.ts", "packages/agent-core/src/providers/providers.test.ts", "packages/agent-core/src/providers/subscription-cli.test.ts", "apps/desktop/src/main/credential-broker.ts"] },
  { id: "provider.routing", category: "providers", capability: "Automatic model, reasoning, latency-tier, cost, and risk routing", referenceProducts: ["openclaw", "hermes", "codex", "claude-code"], status: "implemented", evidence: ["packages/agent-core/src/model-router.ts", "packages/agent-core/src/providers/provider-pool.ts", "packages/agent-core/src/agent-loop.ts", "packages/agent-core/src/agent-core.test.ts", "apps/desktop/src/renderer/App.tsx"] },
  { id: "provider.failover", category: "providers", capability: "Provider fallback, credential pooling, and budget-aware retry", referenceProducts: ["openclaw", "hermes"], status: "implemented", evidence: ["packages/agent-core/src/providers/provider-pool.ts", "packages/agent-core/src/providers/environment.ts", "packages/agent-core/src/providers/providers.test.ts", "packages/agent-core/src/usage-governor.ts", "apps/desktop/src/main/credential-broker.ts", "apps/desktop/src/renderer/App.tsx"] },
  { id: "provider.remote-backends", category: "providers", capability: "Local, Docker, SSH, cluster, and serverless execution backends", referenceProducts: ["openclaw", "hermes", "codex", "claude-code"], status: "implemented", evidence: ["packages/agent-core/src/remote.ts", "packages/agent-core/src/remote.test.ts", "packages/agent-core/src/runtime.ts", "apps/desktop/src/utility/index.ts", "apps/cli/src/state.ts"] },

  { id: "safety.approvals", category: "safety", capability: "Risk-scoped approvals and autonomy controls", referenceProducts: ["openclaw", "hermes", "codex", "claude-code"], status: "implemented", evidence: ["packages/policy-engine/src/index.ts", "packages/agent-core/src/runtime.ts", "packages/agent-core/src/runtime.test.ts", "packages/agent-core/src/agent-loop.ts", "packages/agent-core/src/acp.ts", "apps/desktop/src/renderer/App.tsx", "apps/desktop/src/renderer/components/ApprovalCard.tsx"] },
  { id: "safety.sandbox-scope", category: "safety", capability: "Process isolation, workspace allowlists, and path containment", referenceProducts: ["openclaw", "hermes", "codex", "claude-code"], status: "implemented", evidence: ["apps/desktop/src/main/index.ts", "apps/desktop/src/main/workspace-grant-store.ts", "apps/desktop/src/main/electron-browser-service.ts", "packages/agent-core/src/runtime.ts", "packages/agent-core/src/runtime.test.ts", "packages/agent-core/src/command-runner.ts", "packages/agent-core/src/web-tools.ts", "packages/agent-core/src/web-tools.test.ts", "scripts/smoke-desktop.mjs"] },
  { id: "safety.injection", category: "safety", capability: "Untrusted-content labeling and prompt-injection blocking", referenceProducts: ["openclaw", "hermes", "codex", "claude-code"], status: "implemented", evidence: ["packages/policy-engine/src/index.ts", "packages/policy-engine/src/policy.test.ts", "packages/agent-core/src/runtime.ts", "packages/agent-core/src/agent-loop.ts", "packages/agent-core/src/agent-loop.test.ts", "packages/agent-core/src/web-tools.ts"] },
  { id: "safety.idempotency", category: "safety", capability: "Idempotent mutations with provider read-back verification", referenceProducts: ["openclaw", "hermes", "codex", "claude-code"], status: "implemented", evidence: ["packages/database/src/index.ts", "packages/agent-core/src/index.ts", "packages/agent-core/src/runtime.ts", "packages/agent-core/src/runtime.test.ts", "packages/shared-types/src/contracts.ts"] },
  { id: "safety.credentials", category: "safety", capability: "OS-protected credentials and scoped secret brokering", referenceProducts: ["openclaw", "hermes", "codex", "claude-code"], status: "implemented", evidence: ["apps/desktop/src/main/credential-broker.ts", "apps/desktop/src/main/credential-broker.test.ts", "apps/desktop/src/main/core-supervisor.ts", "apps/desktop/src/main/index.ts", "apps/desktop/src/utility/index.ts", "apps/desktop/src/renderer/App.tsx"] },
  { id: "safety.audit-cost", category: "safety", capability: "Audit trail, usage, cost, concurrency, and admin controls", referenceProducts: ["openclaw", "hermes", "codex", "claude-code"], status: "implemented", evidence: ["packages/database/src/index.ts", "packages/database/migrations/004_agent_loop.sql", "packages/agent-core/src/agent-loop.ts", "packages/agent-core/src/usage-governor.ts", "packages/agent-core/src/usage-governor.test.ts", "packages/agent-core/src/index.ts", "apps/desktop/src/renderer/App.tsx"] },

  { id: "engineering.code-review", category: "engineering", capability: "Repository understanding, code review, CI repair, and PR workflows", referenceProducts: ["hermes", "codex", "claude-code"], status: "implemented", evidence: ["packages/agent-core/src/agent-loop.ts", "packages/agent-core/src/runtime.ts", "packages/agent-core/src/runtime.test.ts", "apps/desktop/src/main/credential-broker.ts"] },
  { id: "engineering.visual-validation", category: "engineering", capability: "Browser-based visual iteration, screenshots, and artifacts", referenceProducts: ["openclaw", "codex", "claude-code"], status: "implemented", evidence: ["packages/agent-core/src/browser-automation.ts", "packages/agent-core/src/browser-automation.test.ts", "apps/desktop/src/main/electron-browser-service.ts", "apps/desktop/src/utility/index.ts", "scripts/smoke-desktop.mjs"] },
  { id: "engineering.migration", category: "engineering", capability: "Import from OpenClaw, Hermes, Codex, and Claude configuration", referenceProducts: ["hermes"], status: "implemented", evidence: ["packages/agent-core/src/administration.ts", "packages/agent-core/src/administration.test.ts", "apps/cli/src/index.ts", "apps/desktop/src/main/index.ts", "apps/desktop/src/renderer/App.tsx", "scripts/smoke-packaged-cli.mjs"] },
  { id: "engineering.enterprise", category: "engineering", capability: "Managed policy, analytics, SSO, and organization controls", referenceProducts: ["codex", "claude-code"], status: "implemented", evidence: ["packages/agent-core/src/administration.ts", "packages/agent-core/src/administration.test.ts", "packages/database/src/index.ts", "apps/cli/src/state.ts", "apps/desktop/src/utility/index.ts", "apps/desktop/src/renderer/App.tsx"] }
];

export function capabilitySummary(): Record<ParityStatus, number> {
  return CAPABILITY_CATALOG.reduce<Record<ParityStatus, number>>((summary, item) => {
    summary[item.status] += 1;
    return summary;
  }, { implemented: 0, partial: 0, planned: 0 });
}
